
name: Turnt Tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install LLVM and Clang (Linux)
        if: runner.os == 'Linux'
        uses: KyleMayes/install-llvm-action@v1.9.0
        with:
          download-url: https://github.com/FreeMasen/llvm-builds/releases/download/v16.0.6
          force-version: true
          ubuntu-version: 20.04
          version: 16.0.6
          directory: ${{ github.workspace }}/llvm
      - name: Install LLVM and Clang (Windows)
        if: runner.os == 'Windows'
        uses: KyleMayes/install-llvm-action@v1.9.0
        with:
          download-url: https://github.com/FreeMasen/llvm-builds/releases/download/v16.0.6
          force-version: true
          directory: C:\LLVM
          version: 16.0.6
      - name: Install LLVM and Clang (MacOS)
        if: runner.os == 'Macos'
        uses: KyleMayes/install-llvm-action@v1.9.0
        with:
          download-url: https://github.com/FreeMasen/llvm-builds/releases/download/v16.0.6
          force-version: true
          version: 16.0.6
          directory: ${{ github.workspace }}/llvm
      - name: update path (MacOS)
        if: runner.os == 'Macos'
        run: echo "${{ github.workspace }}/llvm/bin" >> $GITHUB_PATH
      - name: Install turnt
        run: pip install turnt
      - name: run tests
        run: turnt ./**/turnt.toml
